
query ListPlans @auth(level: PUBLIC) {
    plans {
        name,
        id,
        price,
        maxWine,
        maxTasting,
        description,
        upgradablePlans,
        downgradablePlans,
        isActive,
        trialLength
    }
}

query ListTastings($accountId: UUID) @auth(level: USER) {
  tastings(where: {
    account: { id: { eq: $accountId}}
  }) {
    id,
    accountId,
    name,
    region,
    date,
    notes,
    imageUrl,
    tags,
    varietals,
    rating,
    purchaseLocation,
    price,
    wouldBuyAgain,
  }
}

query GetAccountById($authId: String) @auth(level: USER) {
  accounts(where: {
    authId: {eq: $authId }
  }) {
    firstName,
    lastName,
    avatar,
    displayName,
    authId,
    email,
    onboardingComplete,
    plan { id },
    id
  }
}
