scalar Account_Key
scalar Plan_Key
scalar Regions_Key
scalar Tasting_Key
scalar Varietals_Key
input Account_Data {
  id: UUID
  id_expr: UUID_Expr
  planId: UUID
  planId_expr: UUID_Expr
  plan: Plan_Key
  authId: String
  authId_expr: String_Expr
  avatar: String
  avatar_expr: String_Expr
  displayName: String
  displayName_expr: String_Expr
  email: String
  email_expr: String_Expr
  firstName: String
  firstName_expr: String_Expr
  lastName: String
  lastName_expr: String_Expr
  onboardingComplete: Boolean
}
input Account_Filter {
  _and: [Account_Filter!]
  _not: Account_Filter
  _or: [Account_Filter!]
  id: UUID_Filter
  planId: UUID_Filter
  plan: Plan_Filter
  authId: String_Filter
  avatar: String_Filter
  displayName: String_Filter
  email: String_Filter
  firstName: String_Filter
  lastName: String_Filter
  onboardingComplete: Boolean_Filter
  tastings_on_account: Tasting_ListFilter
}
input Account_ListFilter {
  count: Int_Filter
  exist: Account_Filter
}
input Account_Order {
  id: OrderDirection
  planId: OrderDirection
  authId: OrderDirection
  avatar: OrderDirection
  displayName: OrderDirection
  email: OrderDirection
  firstName: OrderDirection
  lastName: OrderDirection
  onboardingComplete: OrderDirection
}
input Plan_Data {
  id: UUID
  id_expr: UUID_Expr
  description: String
  description_expr: String_Expr
  downgradablePlans: [String!]
  isActive: Boolean
  maxTasting: Int
  maxWine: Int
  name: String
  name_expr: String_Expr
  price: Float
  trialLength: Int
  upgradablePlans: [String!]
}
input Plan_Filter {
  _and: [Plan_Filter!]
  _not: Plan_Filter
  _or: [Plan_Filter!]
  id: UUID_Filter
  description: String_Filter
  downgradablePlans: String_ListFilter
  isActive: Boolean_Filter
  maxTasting: Int_Filter
  maxWine: Int_Filter
  name: String_Filter
  price: Float_Filter
  trialLength: Int_Filter
  upgradablePlans: String_ListFilter
  accounts_on_plan: Account_ListFilter
}
input Plan_ListFilter {
  count: Int_Filter
  exist: Plan_Filter
}
input Plan_Order {
  id: OrderDirection
  description: OrderDirection
  isActive: OrderDirection
  maxTasting: OrderDirection
  maxWine: OrderDirection
  name: OrderDirection
  price: OrderDirection
  trialLength: OrderDirection
}
input Regions_Data {
  id: UUID
  id_expr: UUID_Expr
  country: String
  country_expr: String_Expr
  description: String
  description_expr: String_Expr
  imageUrl: String
  imageUrl_expr: String_Expr
  knownFor: [String!]
  name: String
  name_expr: String_Expr
}
input Regions_Filter {
  _and: [Regions_Filter!]
  _not: Regions_Filter
  _or: [Regions_Filter!]
  id: UUID_Filter
  country: String_Filter
  description: String_Filter
  imageUrl: String_Filter
  knownFor: String_ListFilter
  name: String_Filter
}
input Regions_ListFilter {
  count: Int_Filter
  exist: Regions_Filter
}
input Regions_Order {
  id: OrderDirection
  country: OrderDirection
  description: OrderDirection
  imageUrl: OrderDirection
  name: OrderDirection
}
input Tasting_Data {
  id: UUID
  id_expr: UUID_Expr
  accountId: UUID
  accountId_expr: UUID_Expr
  account: Account_Key
  date: Timestamp
  date_expr: Timestamp_Expr
  date_time: Timestamp_Relative
  imageUrl: String
  imageUrl_expr: String_Expr
  name: String
  name_expr: String_Expr
  notes: String
  notes_expr: String_Expr
  price: Float
  purchaseLocation: String
  purchaseLocation_expr: String_Expr
  rating: Int
  region: String
  region_expr: String_Expr
  tags: [String!]
  varietals: [String!]
  wouldBuyAgain: Boolean
}
input Tasting_Filter {
  _and: [Tasting_Filter!]
  _not: Tasting_Filter
  _or: [Tasting_Filter!]
  id: UUID_Filter
  accountId: UUID_Filter
  account: Account_Filter
  date: Timestamp_Filter
  imageUrl: String_Filter
  name: String_Filter
  notes: String_Filter
  price: Float_Filter
  purchaseLocation: String_Filter
  rating: Int_Filter
  region: String_Filter
  tags: String_ListFilter
  varietals: String_ListFilter
  wouldBuyAgain: Boolean_Filter
}
input Tasting_ListFilter {
  count: Int_Filter
  exist: Tasting_Filter
}
input Tasting_Order {
  id: OrderDirection
  accountId: OrderDirection
  date: OrderDirection
  imageUrl: OrderDirection
  name: OrderDirection
  notes: OrderDirection
  price: OrderDirection
  purchaseLocation: OrderDirection
  rating: OrderDirection
  region: OrderDirection
  wouldBuyAgain: OrderDirection
}
input Varietals_Data {
  id: UUID
  id_expr: UUID_Expr
  characteristics: [String!]
  color: String
  color_expr: String_Expr
  description: String
  description_expr: String_Expr
  imageUrl: String
  imageUrl_expr: String_Expr
  name: String
  name_expr: String_Expr
  recommendedParings: [String!]
}
input Varietals_Filter {
  _and: [Varietals_Filter!]
  _not: Varietals_Filter
  _or: [Varietals_Filter!]
  id: UUID_Filter
  characteristics: String_ListFilter
  color: String_Filter
  description: String_Filter
  imageUrl: String_Filter
  name: String_Filter
  recommendedParings: String_ListFilter
}
input Varietals_ListFilter {
  count: Int_Filter
  exist: Varietals_Filter
}
input Varietals_Order {
  id: OrderDirection
  color: OrderDirection
  description: OrderDirection
  imageUrl: OrderDirection
  name: OrderDirection
}
