extend type Mutation {
  """
  Insert a single Account into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  account_insert(data: Account_Data!): Account_Key!
  """
  Insert a single Plan into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  plan_insert(data: Plan_Data!): Plan_Key!
  """
  Insert a single Regions into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  regions_insert(data: Regions_Data!): Regions_Key!
  """
  Insert a single Tasting into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tasting_insert(data: Tasting_Data!): Tasting_Key!
  """
  Insert a single Varietals into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  varietals_insert(data: Varietals_Data!): Varietals_Key!
  """
  Insert or update a single Account into the table, based on the primary key. Returns the key of the newly inserted Account.
  """
  account_upsert(data: Account_Data!): Account_Key!
  """
  Insert or update a single Plan into the table, based on the primary key. Returns the key of the newly inserted Plan.
  """
  plan_upsert(data: Plan_Data!): Plan_Key!
  """
  Insert or update a single Regions into the table, based on the primary key. Returns the key of the newly inserted Regions.
  """
  regions_upsert(data: Regions_Data!): Regions_Key!
  """
  Insert or update a single Tasting into the table, based on the primary key. Returns the key of the newly inserted Tasting.
  """
  tasting_upsert(data: Tasting_Data!): Tasting_Key!
  """
  Insert or update a single Varietals into the table, based on the primary key. Returns the key of the newly inserted Varietals.
  """
  varietals_upsert(data: Varietals_Data!): Varietals_Key!
  """
  Update a single Account based on `id` or `key`, setting columns specified in `data`. Returns `null` if not found.
  """
  account_update(id: UUID, key: Account_Key, data: Account_Data!): Account_Key
  """
  Update a single Plan based on `id` or `key`, setting columns specified in `data`. Returns `null` if not found.
  """
  plan_update(id: UUID, key: Plan_Key, data: Plan_Data!): Plan_Key
  """
  Update a single Regions based on `id` or `key`, setting columns specified in `data`. Returns `null` if not found.
  """
  regions_update(id: UUID, key: Regions_Key, data: Regions_Data!): Regions_Key
  """
  Update a single Tasting based on `id` or `key`, setting columns specified in `data`. Returns `null` if not found.
  """
  tasting_update(id: UUID, key: Tasting_Key, data: Tasting_Data!): Tasting_Key
  """
  Update a single Varietals based on `id` or `key`, setting columns specified in `data`. Returns `null` if not found.
  """
  varietals_update(id: UUID, key: Varietals_Key, data: Varietals_Data!): Varietals_Key
  """
  Update Account entries matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  account_updateMany(where: Account_Filter, all: Boolean = false, data: Account_Data!): Int!
  """
  Update Plan entries matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  plan_updateMany(where: Plan_Filter, all: Boolean = false, data: Plan_Data!): Int!
  """
  Update Regions entries matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  regions_updateMany(where: Regions_Filter, all: Boolean = false, data: Regions_Data!): Int!
  """
  Update Tasting entries matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  tasting_updateMany(where: Tasting_Filter, all: Boolean = false, data: Tasting_Data!): Int!
  """
  Update Varietals entries matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  varietals_updateMany(where: Varietals_Filter, all: Boolean = false, data: Varietals_Data!): Int!
  """
  Delete a single Account based on `id` or `key` and return its key (or `null` if not found).
  """
  account_delete(id: UUID, key: Account_Key): Account_Key
  """
  Delete a single Plan based on `id` or `key` and return its key (or `null` if not found).
  """
  plan_delete(id: UUID, key: Plan_Key): Plan_Key
  """
  Delete a single Regions based on `id` or `key` and return its key (or `null` if not found).
  """
  regions_delete(id: UUID, key: Regions_Key): Regions_Key
  """
  Delete a single Tasting based on `id` or `key` and return its key (or `null` if not found).
  """
  tasting_delete(id: UUID, key: Tasting_Key): Tasting_Key
  """
  Delete a single Varietals based on `id` or `key` and return its key (or `null` if not found).
  """
  varietals_delete(id: UUID, key: Varietals_Key): Varietals_Key
  """
  Delete Account entries matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  account_deleteMany(where: Account_Filter, all: Boolean = false): Int!
  """
  Delete Plan entries matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  plan_deleteMany(where: Plan_Filter, all: Boolean = false): Int!
  """
  Delete Regions entries matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  regions_deleteMany(where: Regions_Filter, all: Boolean = false): Int!
  """
  Delete Tasting entries matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  tasting_deleteMany(where: Tasting_Filter, all: Boolean = false): Int!
  """
  Delete Varietals entries matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  varietals_deleteMany(where: Varietals_Filter, all: Boolean = false): Int!
}
