type Plan @table {
    name: String!
    price: Float!
    maxWine: Int
    maxTasting: Int
    description: String!
    upgradablePlans: [String]!
    downgradablePlans: [String]!
    isActive: Boolean!
    trialLength: Int!
}

type Account @table {
    firstName: String!
    lastName: String!
    avatar: String
    displayName: String
    authId: String!
    email: String!
    onboardingComplete: Boolean!
    plan: Plan!
}

type Tasting @table {
    account: Account!
    name: String
    region: String!
    date: Timestamp!
    notes: String
    imageUrl: String
    tags: [String]!
    varietals: [String!]!
    rating: Int!
    purchaseLocation: String
    price: Float!
    wouldBuyAgain: Boolean
    createdAt: Timestamp!
    updatedAt: Timestamp!
}

type Varietals @table {
    name: String!
    description: String!
    characteristics: [String!]!
    recommendedParings: [String]!
    color: String!
    imageUrl: String!
}

type Regions @table {
    name: String!
    description: String!
    knownFor: [String!]!
    country: String!
    imageUrl: String!
}